CREATE TABLE ACCOUNT (
    USERNAME TEXT PRIMARY KEY,
    PWSSWORD TEXT NOT NULL,
    NAME TEXT NOT NULL UNIQUE,
    GENDER TEXT, -- male / female
);

CREATE TABLE FOLLOW (
    USERNAME TEXT NOT NULL,
    FOLLOWER TEXT NOT NULL, -- follower USERNAME
    PRIMARY KEY (USERNAME, FOLLOWER) 
);

CREATE TABLE HASHTAG (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TOPIC TEXT NOT NULL,
    CREATOR TEXT NOT NULL -- username
);

CREATE TABLE TWEET (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATOR TEXT NOT NULL, -- username
    CONTENT TEXT NOT NULL
);

CREATE TABLE MENTION (
    TWEETID INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    PRIMARY KEY (TWEETID, USERNAME) 
);

CREATE TABLE TWEET_HASHTAG (
    TWEETID INTEGER NOT NULL,
    HASHTAGID INTEGER NOT NULL,
    PRIMARY KEY (TWEETID, HASHTAGID)
)

CREATE TABLE RETWEET (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    TWEETID INTEGER NOT NULL,
);