CREATE TABLE ACCOUNT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE FOLLOW (
    USERNAME TEXT NOT NULL,
    FOLLOWER TEXT NOT NULL, -- follower username
    PRIMARY KEY (USERNAME, FOLLOWER)
);

CREATE TABLE HASHTAG (
     ID INTEGER PRIMARY KEY AUTOINCREMENT,
     TOPIC TEXT NOT NULL UNIQUE,
     CREATOR TEXT NOT NULL -- username
);

CREATE TABLE TWEET (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATOR TEXT NOT NULL, -- username
    CONTENT TEXT NOT NULL,
    RETWEETID INTEGER
);

CREATE TABLE TWEET_MENTION (
    TWEETID INTEGER NOT NULL,
    USERNAME TEXT NOT NULL,
    PRIMARY KEY (TWEETID, USERNAME)
);

CREATE TABLE TWEET_HASHTAG (
    TWEETID INTEGER NOT NULL,
    HASHTAGID INTEGER NOT NULL,
    PRIMARY KEY (TWEETID, HASHTAGID)
);